### ISSUE TITLE
WA/FB letter

### ISSUE THREAD

**Issue by rcetrangolo** [WHAnonymous/Chat-API#878] opened 2015-07-23 20:51 UTC
Hi, could you give us more info about the letter you received?
You say the project will keep up, right?
Is there some legal issues for us as chat-api users?
Can we know how did you answer the letter?

thank you very much, we're a little bit 'nervous' =)

**Comment by 0xTryCatch** [comment] 2015-07-23 20:59
Duplicate of #794

**Closed by 0xTryCatch** 2015-07-23 20:59 UTC

**Comment by rcetrangolo** [comment] 2015-07-24 13:02
I've read the terms, that's fine, but I want to know if we can be calm about le project's life. Do you assure us it will remain open?

thank you
