### ISSUE TITLE
Last seen value continue changing

### ISSUE THREAD

**Issue by gi097** [WHAnonymous/Chat-API#945] opened 2015-08-23 09:01 UTC
Hello, 

Just a quick question. I'm developing a port from Chat-API for Android, but I'm facing some issues when retrieving the last seen time from a user. For example, I send this request (which I think is correct)

tx: \<iq to="**********@s.whatsapp.net" type="get" xmlns="jabber:iq:last" id="getlastseen-1440320243-1">

After the 'getlastseen-' I use my own current time. However when trying several requests for the same number I get the following seconds responses:

\<query seconds="1989953"></query>
\<query seconds="508627"></query>
\<query seconds="1979322"></query>

So I think something is wrong with the id, any ideas?

**Comment by 0xTryCatch** [comment] 2015-08-23 09:08
Duplicate of #938

**Closed by 0xTryCatch** 2015-08-23 09:08 UTC
